# -*- coding: utf-8 -*-
"""Python_assement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aYqOT9OQUcb_Bdj_AvkSM5CnoVD7PiKz
"""

#List_remove_append
#Description: Remove SPSS from input_list=['SAS', 'R', 'PYTHON', 'SPSS'] and add 'SPARK'in its place.

input_list=['SAS', 'R', 'PYTHON', 'SPSS']
input_list.pop()
input_list.insert(3,'SPARK')
input_list

#String to List Conversion
#Description: Convert a string input_str = 'I love Data Science & Python' to a list by
#splitting it on ‘&’. The sample output for this string will be:

input_str = 'I love Data Science & Python'
input_str.split('&')

#Description: Convert a list ['Pythons syntax is easy to learn', 'Pythons syntax is very
#clear'] to a string using ‘&’. The sample output of this string will be:

lst=['Pythons syntax is easy to learn', 'Pythons syntax is very clear']
str=' & '
str.join(lst)

#Nested List
#Description: Extract Python from a nested list
input_list = [['SAS','R'],['Tableau','SQL'],['Python','Java']]
input_list[2][0]

#It’s the time to disco
#Description: t = ("disco", 12, 4.5)
#What is the output of: t[0][2]

t = ("disco", 12, 4.5)
t[0][2]

#String Palindrome
#Description: Write a program to check whether a string is a palindrome or not. Print 1 if
#the string is a palindrome and 0 otherwise.

def palindrome(stri):
  rev=stri[::-1]
  if (stri==rev):
    return 0
  return 1
palindrome('Any string')

#Reverse Words
#Description: You will be given a sentence in the form of a string. You have to reverse the
#order of the words in the sentence. Remember not to reverse the individual words, but
#the order of words. Check the sample input-output for further clarification.
#Input: A string, which will consist of a few spaces.
#Output: The words in reverse order

def rev_word(strin):
  strin=strin.split(' ')
  strin.reverse()
  return ' '.join(strin)
rev_word("A string, which will consist of a few spaces")

#String Formatting
#Description: Write a program that satisfies below examples
#Input 1: caloRie ConsuMed
#Output 1: calorie_consumed
#Input 2: data science
#Output 2: data_science
#Input 3: datascience
#Output 3: datascience

def format(str):
  return str.replace(' ','_').lower()
format("data science")



"""Multiple Choice Questions
1. How will you extract ‘love’ from the string S = “I love Python”? (More than one
option may be correct.).
a. S[2:5]
**b. S[2:6]**
c. S[3:7]
d. S[-11:-7]
e. S[-11:-8]

Answer:b. S[2:6]

2. What will the output of 3 * 3 ** 3 be?
a. 9
b. 27
**c. 81**
d. 729

Answer:c. 81

3. What will the output be of ((500//7) % 5) ** 3?
**a. 1**
b. 2.91
c. 71.42
d. 0
e. 8

Answer:a. 1

4. If you have a tuple T = (3, 5, 7, 11), what will the output of T.append(9) be?
a. (3, 5, 7, 9, 11)
b. (9, 3, 5, 7, 11)
c. (3, 5, 7, 11, 9)
**d. Error**

Answer: d. Error

5. What will the output of the following program be?
a. Vikas
b. Mahima
c. y
d. A

6. What will the output of the following code be?

1 = [32, 34, 12, 27, 33]
l.append((l4, 19))
print(len(l))

a. 5
**b. 6**
c. 7
d. The code will throw an error

Answer: b.6


7. Which of the following statements is incorrect regarding sets in Python?
a. Sets do not contain duplicate elements
b. Sets are represented using curly braces {}
**c. Sets are immutable**
d. All of the above

Answer: c. Sets are immutable

8. What will the output be of the following code?

D = {l:['Raj', 22), 2:('Simran', 21], 3:['Rahul', 40]}
for val in D:
print(val)

a. 1
2
3

b. [‘Raj’, 22]
[‘Simran’, 21]
[‘Rahul’, 40]

c. 1 [‘Raj’, 22]
2 [‘Simran’, 21]
3 [‘Rahul’, 40]

d. ‘Raj’
‘Simran’
‘Rahul’

Answer:a.1
2
3

9. What will the ‘comprehension equivalent’ be for the following snippet of code?

for sentence in paragraph:
  for word in sentence.split():
    single_word_list.append(word)

a. word for sentence in paragraph for word in sentence.split()
b. [word for sentence in paragraph for word in sentence.split()]
c. word for word in sentence.split() for sentence in paragraph
d. [word for word in sentence.split() for sentence in paragraph]

Answer: d. [word for word in sentence.split() for sentence in paragraph]

10.What will be the output of this code?
print{list(range{l0, 1, -1)))

a. [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
b. [9, 8, 7, 6, 5, 4, 3, 2]
c. [9, 8, 7, 6, 5, 4, 3, 2, 1]
d. [10, 9, 8, 7, 6, 5, 4, 3, 2]

Answer:d. d. [10, 9, 8, 7, 6, 5, 4, 3, 2]
"""